import {
  CircleUserRound,
  File,
  Inbox,
  Landmark,
  LucideIcon,
  Receipt,
  Recycle,
  Send,
  Settings,
  Store,
  UserRound,
  UsersRound,
} from "lucide-react";

export type SidebarItem = {
  title: string;
  icon: LucideIcon;
  variant: "default" | "ghost";
  url: string;
  name: string;
  level: number;
  items: SidebarItem[];
};

export const navItems: SidebarItem[] = [
  {
    title: "Hệ thống",
    icon: Settings,
    variant: "ghost",
    url: "/system",
    name: "System",
    level: 0,
    items: [
      {
        title: "Administrative Division",
        icon: Inbox,
        variant: "ghost",
        url: "/system/administrative-division",
        name: "Administrative Division",
        level: 1,
        items: [
          {
            title: "Provinces",
            icon: Inbox,
            variant: "ghost",
            url: "/system/administrative-division/provinces",
            name: "Provinces",
            level: 2,
            items: [],
          },
        ],
      },
      {
        title: "Bank",
        icon: Inbox,
        variant: "ghost",
        url: "/system/bank",
        name: "Bank",
        level: 1,
        items: [],
      },
      {
        title: "Payment Method",
        icon: Inbox,
        variant: "ghost",
        url: "/system/payment-method",
        name: "Payment Method",
        level: 1,
        items: [],
      },
      {
        title: "Partner",
        icon: Inbox,
        variant: "ghost",
        url: "/system/partner",
        name: "Partner",
        level: 1,
        items: [],
      },
    ],
  },
  {
    title: "Master Merchant",
    icon: Store,
    variant: "ghost",
    url: "/master-merchant",
    name: "Master Merchant",
    level: 0,
    items: [
      {
        title: "Danh sách",
        icon: File,
        variant: "ghost",
        url: "/master-merchant/list",
        name: "Danh sách",
        level: 1,
        items: [],
      },
    ],
  },

  {
    title: "Merchant cá nhân",
    icon: UserRound,
    variant: "ghost",
    url: "/merchant-personal",
    name: "Merchant cá nhân",
    level: 0,
    items: [
      {
        title: "Danh sách",
        icon: File,
        variant: "ghost",
        url: "/merchant-personal/list",
        name: "Danh sách",
        level: 1,
        items: [],
      },
      {
        title: "Branch",
        icon: File,
        variant: "ghost",
        url: "/merchant-personal/branch",
        name: "Branch",
        level: 1,
        items: [
          {
            title: "Danh sách",
            icon: File,
            variant: "ghost",
            url: "/merchant-personal/branch/list",
            name: "Danh sách",
            level: 2,
            items: [],
          },
        ],
      },
      {
        title: "Cashier",
        icon: File,
        variant: "ghost",
        url: "/merchant-personal/cashier",
        name: "Cashier",
        level: 1,
        items: [],
      },
      {
        title: "Quản lý giao dịch",
        icon: File,
        variant: "ghost",
        url: "/merchant-personal/transaction-management",
        name: "Quản lý giao dịch",
        level: 1,
        items: [],
      },
      {
        title: "Quản lý đối tắc",
        icon: File,
        variant: "ghost",
        url: "/merchant-personal/partner-management",
        name: "Quản lý đối tắc",
        level: 1,
        items: [],
      },
      {
        title: "Khuyến mãi",
        icon: File,
        variant: "ghost",
        url: "/merchant-personal/promotion",
        name: "Khuyến mãi",
        level: 1,
        items: [],
      },
    ],
  },
  {
    title: "Merchant doanh nghiệp",
    icon: UsersRound,
    variant: "ghost",
    url: "/merchant-coporation",
    name: "Merchant cá nhân",
    level: 0,
    items: [
      {
        title: "Branch",
        icon: File,
        variant: "ghost",
        url: "/merchant-coporation/branch",
        name: "Branch",
        level: 1,
        items: [],
      },
      {
        title: "Cashier",
        icon: File,
        variant: "ghost",
        url: "/merchant-coporation/cashier",
        name: "Cashier",
        level: 1,
        items: [],
      },
      {
        title: "Quản lý giao dịch",
        icon: File,
        variant: "ghost",
        url: "/merchant-coporation/transaction-management",
        name: "Quản lý giao dịch",
        level: 1,
        items: [],
      },
      {
        title: "Quản lý đối tác",
        icon: File,
        variant: "ghost",
        url: "/merchant-coporation/partner-management",
        name: "Quản lý đối tác",
        level: 1,
        items: [],
      },
      {
        title: "Khuyến mãi",
        icon: File,
        variant: "ghost",
        url: "/merchant-coporation/promotion",
        name: "Khuyến mãi",
        level: 1,
        items: [],
      },
    ],
  },
  {
    title: "Demo",
    icon: UsersRound,
    variant: "ghost",
    url: "/demo",
    name: "Demo",
    level: 0,
    items: [],
  },
];
